version: '3.1'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
        tmpfs:
          size: 100000000
    ports:
      - 5432:5432

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["start", "--import-realm"]
    restart: unless-stopped
    environment:
      # Host config
      KC_HOSTNAME: mykeycloak
      KC_PROXY: edge

      # TLS config
      HTTPS_CERTIFICATE_FILE: /opt/keycloak/data/keys/keycloak-server.crt.pem
      HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/data/keys/keycloak-server.key.pem
      HTTPS_PORT: 8081

      # DB config
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password      
      
       # Admin user config
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Other
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    ports:
      - 8180:8080
      - 8081:8081
      - 8443:8443
    volumes:
      - ./config/:/opt/keycloak/data/import:ro
      - ./keys/:/opt/keycloak/data/keys:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
